/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "collection.list", input: never, result: Array<Collection> } | 
        { key: "collection.read", input: number, result: Collection | null } | 
        { key: "item.list", input: number | null, result: Array<Item> } | 
        { key: "item.read", input: number, result: Item | null },
    mutations: 
        { key: "collection.create", input: string, result: Collection } | 
        { key: "collection.delete", input: number, result: Collection } | 
        { key: "collection.update", input: CollectionUpdateArgs, result: Collection } | 
        { key: "item.create", input: ItemCreateArgs, result: Item } | 
        { key: "item.delete", input: number, result: Item } | 
        { key: "item.update", input: ItemUpdateArgs, result: Item },
    subscriptions: never
};

export interface Collection { id: number, name: string, createdAt: string, updatedAt: string }

export interface CollectionUpdateArgs { id: number, name: string }

export interface Item { id: number, title: string, completed: boolean, createdAt: string, collectionId: number | null }

export interface ItemCreateArgs { title: string, collection_id: number }

export interface ItemUpdateArgs { id: number, title: string, completed: boolean }
